### ISSUE TITLE
Line 172 of GameManager.cs

### ISSUE THREAD

**Issue by TacoOblivion** [elierodrigue/PSClassicTool#3]
It assumes that the drive has a folder called "games" on it and was causing 1.3 to crash before it even opened up for me.

```
System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=Could not find a part of the path 'E:\games'.
  Source=mscorlib
  StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at GameManager.ListGames() in C:\PSClassic\PSClassicTool-master\PSClassicTool\Managers\GameManager.cs:line 172
   at PSClassicTool.Form1.LoadData(String baseFolder) in C:\PSClassic\PSClassicTool-master\PSClassicTool\Form1.cs:line 104
   at PSClassicTool.Form1.SelectDrive(DriveInfo di) in C:\PSClassic\PSClassicTool-master\PSClassicTool\Form1.cs:line 84
   at PSClassicTool.Form1.LoadDrives() in C:\PSClassic\PSClassicTool-master\PSClassicTool\Form1.cs:line 74
   at PSClassicTool.Form1..ctor() in C:\PSClassic\PSClassicTool-master\PSClassicTool\Form1.cs:line 14
   at PSClassicTool.Program.Main() in C:\PSClassic\PSClassicTool-master\PSClassicTool\Program.cs:line 19
```

**Comment by elierodrigue** [comment]
Make sure your usb drive already have bleemsync installed.

**Comment by elierodrigue** [comment]
*Its going to be fixed in the next version.
